const dataStatsGet = {
  data: [
    {
      keyword: "black car",
      id: 604330,
      countryCode: "us",
      updateDate: "2020-04-07T09:22:17.544132+00:00",
      updateDateIpad: "2020-04-07T09:22:19.016918+00:00",
      isCompleted: true,
      canStartCampaign: 0,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: "-", change: null },
      total_apps: 857,
      users_per_day: 23,
      ipad_position_info: { position: "-", change: null },
      ipad_total_apps: 189,
      searchads_popularity: 5,
      suggestions_count: {},
      timestamp: "-",
      color: 0,
      translation: "black car",
      translation_from: "en",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "cab",
      id: 231069,
      countryCode: "us",
      updateDate: "2020-04-07T10:59:45.857548+00:00",
      updateDateIpad: "2020-04-07T10:59:48.194864+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: 9, change: 1 },
      total_apps: 5242,
      users_per_day: 67,
      ipad_position_info: { position: 7, change: 0 },
      ipad_total_apps: 2491,
      searchads_popularity: 30,
      suggestions_count: 12,
      timestamp: "-",
      color: 0,
      translation: "cab",
      translation_from: "en",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "cab app",
      id: 604298,
      countryCode: "us",
      updateDate: "2020-04-07T09:21:29.509579+00:00",
      updateDateIpad: "2020-04-07T09:21:30.950641+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: 12, change: -2 },
      total_apps: 5238,
      users_per_day: 45,
      ipad_position_info: { position: 1, change: 0 },
      ipad_total_apps: 2488,
      searchads_popularity: 14,
      suggestions_count: 8,
      timestamp: "-",
      color: 0,
      translation: "cab app",
      translation_from: "en",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "call taxi",
      id: 2590052,
      countryCode: "us",
      updateDate: "2020-04-07T11:51:59.600124+00:00",
      updateDateIpad: "2020-04-07T11:52:00.959562+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: 7, change: 0 },
      total_apps: 297,
      users_per_day: 0,
      ipad_position_info: { position: 1, change: 0 },
      ipad_total_apps: 164,
      searchads_popularity: 5,
      suggestions_count: 5,
      timestamp: "-",
      color: 0,
      translation: "call taxi",
      translation_from: "en",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "gett",
      id: 231076,
      countryCode: "us",
      updateDate: "2020-04-07T10:59:56.630643+00:00",
      updateDateIpad: "2020-04-07T10:59:58.425796+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: 10, change: 1 },
      total_apps: 29,
      users_per_day: 148,
      ipad_position_info: { position: 2, change: 1 },
      ipad_total_apps: 15,
      searchads_popularity: 30,
      suggestions_count: 11,
      timestamp: "-",
      color: 0,
      translation: "given",
      translation_from: "sv",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "gettaxi",
      id: 2403914,
      countryCode: "us",
      updateDate: "2020-04-07T11:40:32.671880+00:00",
      updateDateIpad: "2020-04-07T11:40:34.248874+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: 2, change: 1 },
      total_apps: 225,
      users_per_day: 45,
      ipad_position_info: { position: 1, change: 0 },
      ipad_total_apps: 96,
      searchads_popularity: 5,
      suggestions_count: 1,
      timestamp: "-",
      color: 0,
      translation: "gettaxi",
      translation_from: "en",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "go home",
      id: 2590069,
      countryCode: "us",
      updateDate: "2020-04-07T11:52:13.213216+00:00",
      updateDateIpad: "2020-04-07T11:52:14.962631+00:00",
      isCompleted: true,
      canStartCampaign: 0,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: "-", change: null },
      total_apps: 27696,
      users_per_day: 53,
      ipad_position_info: { position: "-", change: null },
      ipad_total_apps: 17790,
      searchads_popularity: 20,
      suggestions_count: 10,
      timestamp: "-",
      color: 0,
      translation: "go home",
      translation_from: "en",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "grab car",
      id: 2384680,
      countryCode: "us",
      updateDate: "2020-04-06T21:43:53.785360+00:00",
      updateDateIpad: "2020-04-06T21:43:54.972795+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: 7, change: 0 },
      total_apps: 1018,
      users_per_day: 45,
      ipad_position_info: { position: 11, change: 0 },
      ipad_total_apps: 693,
      searchads_popularity: 5,
      suggestions_count: 3,
      timestamp: "-",
      color: 0,
      translation: "grab car",
      translation_from: "en",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "grabtaxi",
      id: 2393286,
      countryCode: "us",
      updateDate: "2020-04-07T15:29:35.309116+00:00",
      updateDateIpad: "2020-04-07T15:29:36.590852+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: 11, change: 0 },
      total_apps: 1025,
      users_per_day: 45,
      ipad_position_info: { position: 7, change: 0 },
      ipad_total_apps: 694,
      searchads_popularity: 5,
      suggestions_count: 1,
      timestamp: "-",
      color: 0,
      translation: "grabtaxi",
      translation_from: "en",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "grab taxi",
      id: 604340,
      countryCode: "us",
      updateDate: "2020-04-07T09:22:32.110107+00:00",
      updateDateIpad: "2020-04-07T09:22:33.096514+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: 5, change: 1 },
      total_apps: 1034,
      users_per_day: 69,
      ipad_position_info: { position: 4, change: 0 },
      ipad_total_apps: 698,
      searchads_popularity: 20,
      suggestions_count: 2,
      timestamp: "-",
      color: 0,
      translation: "grab taxi",
      translation_from: "en",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "local taxi",
      id: 2590071,
      countryCode: "us",
      updateDate: "2020-04-07T11:52:17.625966+00:00",
      updateDateIpad: "2020-04-07T11:52:19.688023+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: 4, change: 0 },
      total_apps: 22837,
      users_per_day: 0,
      ipad_position_info: { position: 2, change: 0 },
      ipad_total_apps: 14795,
      searchads_popularity: 5,
      suggestions_count: 1,
      timestamp: "-",
      color: 0,
      translation: "local taxi",
      translation_from: "en",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "lyft",
      id: 2518600,
      countryCode: "us",
      updateDate: "2020-04-07T04:15:16.271112+00:00",
      updateDateIpad: "2020-04-07T04:15:17.461332+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: 4, change: 0 },
      total_apps: 59,
      users_per_day: 8987,
      ipad_position_info: { position: 1, change: 0 },
      ipad_total_apps: 34,
      searchads_popularity: 73,
      suggestions_count: 10,
      timestamp: "-",
      color: 0,
      translation: "lift",
      translation_from: "sv",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "lyft app",
      id: 2518786,
      countryCode: "us",
      updateDate: "2020-04-07T11:47:49.620285+00:00",
      updateDateIpad: "2020-04-07T11:47:50.516751+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: 2, change: 0 },
      total_apps: 58,
      users_per_day: 148,
      ipad_position_info: { position: 1, change: 0 },
      ipad_total_apps: 32,
      searchads_popularity: 37,
      suggestions_count: 3,
      timestamp: "-",
      color: 0,
      translation: "lifting ideas",
      translation_from: "sv",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "new york",
      id: 477298,
      countryCode: "us",
      updateDate: "2020-04-06T18:23:56.223750+00:00",
      updateDateIpad: "2020-04-06T18:23:58.378340+00:00",
      isCompleted: true,
      canStartCampaign: 0,
      isAppstore: true,
      is_clustered_search_result: true,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: "-", change: null },
      total_apps: 4990,
      users_per_day: 73,
      ipad_position_info: { position: "-", change: null },
      ipad_total_apps: 3278,
      searchads_popularity: 32,
      suggestions_count: 12,
      timestamp: "-",
      color: 0,
      translation: "new york",
      translation_from: "en",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "nyc taxi app",
      id: 2590048,
      countryCode: "us",
      updateDate: "2020-04-07T11:51:53.210751+00:00",
      updateDateIpad: "2020-04-07T11:51:54.801121+00:00",
      isCompleted: true,
      canStartCampaign: 0,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: "-", change: null },
      total_apps: 50,
      users_per_day: 25,
      ipad_position_info: { position: "-", change: null },
      ipad_total_apps: 39,
      searchads_popularity: 5,
      suggestions_count: 1,
      timestamp: "-",
      color: 0,
      translation: "nyc taxi app",
      translation_from: "en",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "ny taxi",
      id: 603722,
      countryCode: "us",
      updateDate: "2020-04-07T09:16:57.617070+00:00",
      updateDateIpad: "2020-04-07T09:16:58.881904+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: 6, change: 0 },
      total_apps: 22822,
      users_per_day: 16,
      ipad_position_info: { position: 2, change: 0 },
      ipad_total_apps: 14789,
      searchads_popularity: 5,
      suggestions_count: 1,
      timestamp: "-",
      color: 0,
      translation: "the taxi",
      translation_from: "mg",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "ride",
      id: 604296,
      countryCode: "us",
      updateDate: "2020-04-06T19:23:55.502411+00:00",
      updateDateIpad: "2020-04-06T19:23:57.515982+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: true,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: 12, change: 0 },
      total_apps: 11307,
      users_per_day: 148,
      ipad_position_info: { position: 32, change: 0 },
      ipad_total_apps: 7444,
      searchads_popularity: 39,
      suggestions_count: 10,
      timestamp: "-",
      color: 0,
      translation: "ride",
      translation_from: "en",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "rideshare",
      id: 2353052,
      countryCode: "us",
      updateDate: "2020-04-07T14:33:55.298089+00:00",
      updateDateIpad: "2020-04-07T14:33:56.324544+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: 11, change: 1 },
      total_apps: 1243,
      users_per_day: 73,
      ipad_position_info: { position: 2, change: -1 },
      ipad_total_apps: 486,
      searchads_popularity: 31,
      suggestions_count: 10,
      timestamp: "-",
      color: 0,
      translation: "rideshare",
      translation_from: "en",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "ridesharing",
      id: 230720,
      countryCode: "us",
      updateDate: "2020-04-07T09:53:15.164358+00:00",
      updateDateIpad: "2020-04-07T09:53:16.187556+00:00",
      isCompleted: true,
      canStartCampaign: 0,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: "-", change: null },
      total_apps: 239,
      users_per_day: 0,
      ipad_position_info: { position: "-", change: null },
      ipad_total_apps: 73,
      searchads_popularity: 5,
      suggestions_count: 10,
      timestamp: "-",
      color: 0,
      translation: "ridesharing",
      translation_from: "en",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "share",
      id: 477904,
      countryCode: "us",
      updateDate: "2020-04-07T10:57:21.477805+00:00",
      updateDateIpad: "2020-04-07T10:57:23.338400+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: 42, change: -2 },
      total_apps: 17764,
      users_per_day: 148,
      ipad_position_info: { position: 37, change: 0 },
      ipad_total_apps: 9880,
      searchads_popularity: 42,
      suggestions_count: 11,
      timestamp: "-",
      color: 0,
      translation: "share",
      translation_from: "en",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "share taxi",
      id: 2590057,
      countryCode: "us",
      updateDate: "2020-04-07T11:52:02.997839+00:00",
      updateDateIpad: "2020-04-07T11:52:04.050109+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: 1, change: 0 },
      total_apps: 430,
      users_per_day: 0,
      ipad_position_info: { position: 1, change: 0 },
      ipad_total_apps: 154,
      searchads_popularity: 5,
      suggestions_count: 3,
      timestamp: "-",
      color: 0,
      translation: "share taxi",
      translation_from: "en",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "sharing",
      id: 482662,
      countryCode: "us",
      updateDate: "2020-04-07T10:58:32.584406+00:00",
      updateDateIpad: "2020-04-07T10:58:35.134194+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: 66, change: 1 },
      total_apps: 17313,
      users_per_day: 39,
      ipad_position_info: { position: 22, change: 0 },
      ipad_total_apps: 9563,
      searchads_popularity: 18,
      suggestions_count: 12,
      timestamp: "-",
      color: 0,
      translation: "sharing",
      translation_from: "en",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "sidecar",
      id: 2357078,
      countryCode: "us",
      updateDate: "2020-04-06T21:39:19.929068+00:00",
      updateDateIpad: "2020-04-06T21:39:21.408625+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: 23, change: 0 },
      total_apps: 713,
      users_per_day: 77,
      ipad_position_info: { position: 6, change: 0 },
      ipad_total_apps: 238,
      searchads_popularity: 43,
      suggestions_count: 4,
      timestamp: "-",
      color: 0,
      translation: "sidecar",
      translation_from: "en",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "siri",
      id: 194,
      countryCode: "us",
      updateDate: "2020-04-06T19:24:10.600125+00:00",
      updateDateIpad: "2020-04-06T19:24:12.362368+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: true,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: 9, change: 0 },
      total_apps: 1281,
      users_per_day: 431,
      ipad_position_info: { position: 10, change: 0 },
      ipad_total_apps: 732,
      searchads_popularity: 48,
      suggestions_count: {},
      timestamp: "-",
      color: 0,
      translation: "siri",
      translation_from: "en",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "taxi",
      id: 226921,
      countryCode: "us",
      updateDate: "2020-04-07T11:34:53.968504+00:00",
      updateDateIpad: "2020-04-07T11:34:55.893469+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: true,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: 20, change: -1 },
      total_apps: 23373,
      users_per_day: 509,
      ipad_position_info: { position: 51, change: 2 },
      ipad_total_apps: 15105,
      searchads_popularity: 47,
      suggestions_count: 10,
      timestamp: "-",
      color: 0,
      translation: "taxi",
      translation_from: "en",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "taxi app",
      id: 604272,
      countryCode: "us",
      updateDate: "2020-04-07T09:21:01.172424+00:00",
      updateDateIpad: "2020-04-07T09:21:02.972797+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: 7, change: 1 },
      total_apps: 23329,
      users_per_day: 55,
      ipad_position_info: { position: 2, change: 0 },
      ipad_total_apps: 15075,
      searchads_popularity: 19,
      suggestions_count: 10,
      timestamp: "-",
      color: 0,
      translation: "taxi app",
      translation_from: "en",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "taxi apps",
      id: 603154,
      countryCode: "us",
      updateDate: "2020-04-07T09:18:49.519617+00:00",
      updateDateIpad: "2020-04-07T09:18:51.113988+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: 10, change: -2 },
      total_apps: 23343,
      users_per_day: 31,
      ipad_position_info: { position: 5, change: 0 },
      ipad_total_apps: 15079,
      searchads_popularity: 8,
      suggestions_count: 2,
      timestamp: "-",
      color: 0,
      translation: "taxi apps",
      translation_from: "en",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "taxi cab app",
      id: 604270,
      countryCode: "us",
      updateDate: "2020-04-07T09:20:57.665298+00:00",
      updateDateIpad: "2020-04-07T09:20:59.347675+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: 9, change: 0 },
      total_apps: 5736,
      users_per_day: 0,
      ipad_position_info: { position: 1, change: 0 },
      ipad_total_apps: 3229,
      searchads_popularity: 5,
      suggestions_count: {},
      timestamp: "-",
      color: 0,
      translation: "taxi cab app",
      translation_from: "en",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "taxis",
      id: 604300,
      countryCode: "us",
      updateDate: "2020-04-07T09:21:34.087473+00:00",
      updateDateIpad: "2020-04-07T09:21:35.580710+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: true,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: 13, change: -1 },
      total_apps: 23716,
      users_per_day: 37,
      ipad_position_info: { position: 34, change: -1 },
      ipad_total_apps: 15239,
      searchads_popularity: 17,
      suggestions_count: 10,
      timestamp: "-",
      color: 0,
      translation: "taxis",
      translation_from: "en",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "taxi service",
      id: 2590075,
      countryCode: "us",
      updateDate: "2020-04-07T11:52:23.421089+00:00",
      updateDateIpad: "2020-04-07T11:52:25.483030+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: 5, change: 1 },
      total_apps: 22855,
      users_per_day: 31,
      ipad_position_info: { position: 2, change: 0 },
      ipad_total_apps: 14825,
      searchads_popularity: 6,
      suggestions_count: 10,
      timestamp: "-",
      color: 0,
      translation: "taxi service",
      translation_from: "en",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "transit app",
      id: 2395832,
      countryCode: "us",
      updateDate: "2020-04-07T16:31:44.341037+00:00",
      updateDateIpad: "2020-04-07T16:31:45.827381+00:00",
      isCompleted: true,
      canStartCampaign: 0,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: "-", change: null },
      total_apps: 2601,
      users_per_day: 67,
      ipad_position_info: { position: "-", change: null },
      ipad_total_apps: 1752,
      searchads_popularity: 27,
      suggestions_count: 10,
      timestamp: "-",
      color: 0,
      translation: "transit app",
      translation_from: "en",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "uber",
      id: 230726,
      countryCode: "us",
      updateDate: "2020-04-07T09:53:17.768641+00:00",
      updateDateIpad: "2020-04-07T09:53:18.931507+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: 1, change: 0 },
      total_apps: 414,
      users_per_day: 13330,
      ipad_position_info: { position: 1, change: 0 },
      ipad_total_apps: 219,
      searchads_popularity: 77,
      suggestions_count: 10,
      timestamp: "-",
      color: 0,
      translation: "uber",
      translation_from: "en",
      in_name: { count: 1, full: true },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "uber app",
      id: 603714,
      countryCode: "us",
      updateDate: "2020-04-07T09:16:48.854503+00:00",
      updateDateIpad: "2020-04-07T09:16:50.192198+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: 1, change: 0 },
      total_apps: 5570,
      users_per_day: 122,
      ipad_position_info: { position: 1, change: 0 },
      ipad_total_apps: 3481,
      searchads_popularity: 37,
      suggestions_count: 4,
      timestamp: "-",
      color: 0,
      translation: "uber app",
      translation_from: "de",
      in_name: { count: 1, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "uber app free",
      id: 606214,
      countryCode: "us",
      updateDate: "2020-04-07T09:27:24.129304+00:00",
      updateDateIpad: "2020-04-07T09:27:25.570347+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: 1, change: 0 },
      total_apps: 239,
      users_per_day: 55,
      ipad_position_info: { position: 1, change: 0 },
      ipad_total_apps: 134,
      searchads_popularity: 18,
      suggestions_count: 1,
      timestamp: "-",
      color: 0,
      translation: "uber app free",
      translation_from: "en",
      in_name: { count: 1, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "uber driver app",
      id: 2501732,
      countryCode: "us",
      updateDate: "2020-04-07T14:26:02.786438+00:00",
      updateDateIpad: "2020-04-07T14:26:03.747546+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: 3, change: 0 },
      total_apps: 415,
      users_per_day: 3032,
      ipad_position_info: { position: 3, change: 0 },
      ipad_total_apps: 224,
      searchads_popularity: 65,
      suggestions_count: 2,
      timestamp: "-",
      color: 0,
      translation: "uber driver app",
      translation_from: "en",
      in_name: { count: 1, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "ubereats",
      id: 604938,
      countryCode: "us",
      updateDate: "2020-04-07T09:54:50.794619+00:00",
      updateDateIpad: "2020-04-07T09:54:51.767569+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: 10, change: 1 },
      total_apps: 552,
      users_per_day: 599,
      ipad_position_info: { position: 7, change: 1 },
      ipad_total_apps: 305,
      searchads_popularity: 52,
      suggestions_count: 5,
      timestamp: "-",
      color: 0,
      translation: "ubereats",
      translation_from: "ca",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "uber eats",
      id: 603716,
      countryCode: "us",
      updateDate: "2020-04-06T17:38:08.262212+00:00",
      updateDateIpad: "2020-04-06T17:38:09.782173+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: 9, change: 0 },
      total_apps: 549,
      users_per_day: 8987,
      ipad_position_info: { position: 7, change: 0 },
      ipad_total_apps: 298,
      searchads_popularity: 81,
      suggestions_count: 10,
      timestamp: "-",
      color: 0,
      translation: "uber eats",
      translation_from: "en",
      in_name: { count: 1, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "yellow cab",
      id: 606220,
      countryCode: "us",
      updateDate: "2020-04-07T09:27:33.580415+00:00",
      updateDateIpad: "2020-04-07T09:27:34.498265+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: 6, change: 0 },
      total_apps: 184,
      users_per_day: 77,
      ipad_position_info: { position: 7, change: 1 },
      ipad_total_apps: 146,
      searchads_popularity: 29,
      suggestions_count: 10,
      timestamp: "-",
      color: 0,
      translation: "yellow cab",
      translation_from: "en",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "yellow cab app",
      id: 2501734,
      countryCode: "us",
      updateDate: "2020-04-06T22:23:09.868599+00:00",
      updateDateIpad: "2020-04-06T22:23:11.400030+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: 10, change: 0 },
      total_apps: 176,
      users_per_day: 33,
      ipad_position_info: { position: 1, change: 0 },
      ipad_total_apps: 142,
      searchads_popularity: 9,
      suggestions_count: 1,
      timestamp: "-",
      color: 0,
      translation: "yellow cab app",
      translation_from: "en",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "yellow cab austin",
      id: 2501740,
      countryCode: "us",
      updateDate: "2020-04-07T14:26:07.451253+00:00",
      updateDateIpad: "2020-04-07T14:26:08.633934+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: 4, change: 0 },
      total_apps: 167,
      users_per_day: 0,
      ipad_position_info: { position: 1, change: 0 },
      ipad_total_apps: 132,
      searchads_popularity: 5,
      suggestions_count: {},
      timestamp: "-",
      color: 0,
      translation: "yellow cab austin",
      translation_from: "en",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "yellow cab nyc",
      id: 2501738,
      countryCode: "us",
      updateDate: "2020-04-06T22:23:13.945484+00:00",
      updateDateIpad: "2020-04-06T22:23:16.357579+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: 7, change: 0 },
      total_apps: 189,
      users_per_day: 0,
      ipad_position_info: { position: 1, change: 0 },
      ipad_total_apps: 148,
      searchads_popularity: 5,
      suggestions_count: {},
      timestamp: "-",
      color: 0,
      translation: "yellow cab nyc",
      translation_from: "en",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
    {
      keyword: "yellow cab of dc",
      id: 2501750,
      countryCode: "us",
      updateDate: "2020-04-07T14:26:25.569070+00:00",
      updateDateIpad: "2020-04-07T14:26:26.713704+00:00",
      isCompleted: true,
      canStartCampaign: true,
      isAppstore: true,
      is_clustered_search_result: false,
      is_keywordstats_outdated: false,
      note: "",
      favorite: false,
      custom_traffic_score: null,
      position_info: { position: 2, change: 0 },
      total_apps: 167,
      users_per_day: 0,
      ipad_position_info: { position: 1, change: 0 },
      ipad_total_apps: 132,
      searchads_popularity: 5,
      suggestions_count: {},
      timestamp: "-",
      color: 0,
      translation: "yellow cab of dc",
      translation_from: "en",
      in_name: { count: 0, full: false },
      in_subtitle: { count: 0, full: false },
      best_rank: null,
      ipad_best_rank: null,
    },
  ],
  tabs: [],
  has_available_keywords: true,
  pages: 0,
  recordsTotal: 42,
  recordsFiltered: 42,
  result: "ok",
};

export { dataStatsGet };
